### ISSUE TITLE
Extact method to get password

### ISSUE THREAD

**Issue by lwolf83** [lwolf83/Project2-Banque#40]
https://github.com/lwolf83/Project2-Banque/blob/f641b495b241ee1e66d104b49626c8c09c51cb0d/ConsoleApp/Program.cs#L149-L161

Déplacer cette partie dans une nouvelle fonction.
Cette fonction ne s'occupe que de gérer la saisie au clavier du mot de passe.

**Comment by JeanBarthelemy** [comment]
fixed issue#40
