### ISSUE TITLE
Encodage du mot de passe

### ISSUE THREAD

**Issue by Laure90** [lwolf83/Project2-Banque#50]
Lorsque je crée un utilisateur et que je renseigne dans son mot de passe certains caractères spéciaux (€, ^, ¨ ...) sont mal encodés.

La solution à ce problème est de spécifier le bon charset (utf8) lors de la connexion à la base de données.

[https://docs.microsoft.com/en-us/sql/connect/php/connection-options?view=sql-server-ver15](https://docs.microsoft.com/en-us/sql/connect/php/connection-options?view=sql-server-ver15)

**Comment by JeanBarthelemy** [comment]
fixed issue thanks to Elif's function who hides the password and read each character instead of reading a string

**Comment by JeanBarthelemy** [comment]
fixed issue thanks to Elif's function who hides the password and read each character instead of reading a string
