### ISSUE TITLE
Hash des mots de passe

### ISSUE THREAD

**Issue by Laure90** [lwolf83/Project2-Banque#51]
Actuellement, les mots de passes sont stockés et comparés en clair.

Il faut pour des raisons de sécurité que les mots de passes soient stockés de manière chiffrée et comparé de manière chiffrée.

Pour cela, on va utiliser l'algorithme SHA-256 pour crypter les mots de passe.

[https://docs.microsoft.com/fr-fr/dotnet/api/system.security.cryptography.sha256?view=netframework-4.8](https://docs.microsoft.com/fr-fr/dotnet/api/system.security.cryptography.sha256?view=netframework-4.8)

**Comment by lwolf83** [comment]
Ajout de la fonction de hash
