### ISSUE TITLE
Stopper le program lorsque la connection échoue

### ISSUE THREAD

**Issue by lwolf83** [lwolf83/Project2-Banque#73]
La commande createaccount -l aurent -s crée un compte alors que le compte 'aurent'  n'existe pas.

Il faut que la fonction connexion stop le programme si il y a un problème (mauvais mot de passe, compte inexistant, etc).

**Comment by JeanBarthelemy** [comment]
La fonction Connection() du RunCreateAccount a été mise dans une condition (login existant dans base de données). Une sortie du terminal a été implémentée, si le login n'est pas dans la base de données ou si le mot de passe n'est pas bon.
