### ISSUE TITLE
Option createaccount

### ISSUE THREAD

**Issue by prevostcorentin** [lwolf83/Project2-Banque#80]
Lorsque j'utilise le verbe `createaccount`, je peux ne pas spécifier le type de compte et ça ne m'affiche rien, comme si ça avait marché.

Il faut rendre obligatoire la présence du type de compte à créer.

Pour cela, plutôt d'utiliser deux options distinces (--sa/--ca), créez une option -t/--account-type qui prend en argument le type de compte (SA ou CA mais pas autre chose).

**Comment by Elifinanc** [comment]
resolve issu 80 :  option createaccount with 't' - "type" to precise account type with a following string sa/ca
